version: "3.7"

services: 
  web:
    build: .
    restart: unless-stopped
    image: nss_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

    depends_on:
      - db
    
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - nss-datas:/var/lib/postgresql
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

volumes:
  nss-datas:


